# Generated by Django 4.0.4 on 2022-06-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_logins_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='a', upload_to='userimages/'),
            preserve_default=False,
        ),
    ]
