# Generated by Django 4.0.4 on 2022-06-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='logins',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
