# Generated by Django 4.0.4 on 2022-06-10 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_logins_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.leader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='user.user')),
            ],
        ),
    ]
