# Generated by Django 4.0.4 on 2022-06-10 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_leaderuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 10, 22, 24, 2, 555720, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
