# Generated by Django 4.0.4 on 2022-06-10 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user.leader'),
        ),
        migrations.DeleteModel(
            name='LeaderUser',
        ),
    ]
